In [2]:
import numpy as np

#Creación y Indexación:

1 - Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [4]:
array_1d=np.random.randint(10,100, 50)
array_1d

array([17, 52, 59, 18, 31, 25, 63, 61, 74, 67, 13, 59, 18, 82, 40, 51, 33,
       44, 78, 14, 51, 27, 99, 35, 39, 83, 26, 73, 82, 58, 94, 25, 31, 36,
       10, 65, 69, 35, 82, 45, 11, 75, 29, 34, 56, 82, 80, 60, 11, 99])

In [8]:
array_1d[::5]

array([17, 25, 13, 51, 51, 83, 94, 65, 11, 82])

2 - Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [20]:
array_2=np.random.randint(1,20, 30)
array_2

array([ 2,  6,  2, 10,  9,  6, 18, 14, 11,  1, 10,  4, 14, 19,  9, 17,  7,
        4, 11, 10, 16,  7, 17,  9,  8,  7, 12,  8, 12, 10])

In [21]:
array_2[1::2]

array([ 6, 10,  6, 14,  1,  4, 19, 17,  4, 10,  7,  9,  7,  8, 10])

3 - Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [23]:
array_2d=np.random.randint(0, 20, (4,6))
array_2d



array([[ 2,  9,  7, 11,  9, 10],
       [18, 15, 19, 18, 13,  9],
       [ 2,  0, 13, 11, 18, 12],
       [ 6,  9,  4,  9,  8, 17]])

In [24]:
array_decimales=np.random.rand(4,6)

In [25]:
array_2d_decimales=np.add(array_2d, array_decimales)
array_2d_decimales

array([[ 2.895753  ,  9.48222957,  7.40577553, 11.04629813,  9.52242022,
        10.90158996],
       [18.43276306, 15.38184734, 19.68584502, 18.48741362, 13.40216466,
         9.59648994],
       [ 2.72162573,  0.15113173, 13.63598017, 11.58282711, 18.31159285,
        12.07937066],
       [ 6.22463541,  9.35651391,  4.90991735,  9.43671199,  8.97873748,
        17.95401433]])

4 - Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [30]:
array_3=np.random.rand(4,6)


In [32]:
array_3round=np.round(array_3, 2)
array_3round

array([[0.95, 0.49, 0.47, 0.12, 0.33, 0.85],
       [0.62, 0.5 , 0.28, 0.77, 0.38, 0.57],
       [0.89, 0.29, 0.4 , 0.93, 0.97, 0.98],
       [0.34, 0.99, 0.15, 0.65, 0.34, 0.68]])

In [35]:
array_3round[:,1]

array([0.49, 0.5 , 0.29, 0.99])

5 - Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [37]:
array_4=np.random.randint(-50, 51, 30)
array_4

array([-30,   1,  28,  47,  43,  -5,  39, -26, -49,  34,  -9,  -9,  46,
        42,  42, -12,  48,  35,  50,  10, -48, -17, -19,  13,   9,   5,
       -32,  30, -41, -40])

In [38]:
array_4[array_4<0]

array([-30,  -5, -26, -49,  -9,  -9, -12, -48, -17, -19, -32, -41, -40])

6 - Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [53]:
array_5=np.round(np.random.rand(10),2)
array_5

array([0.93, 0.95, 0.11, 0.54, 0.03, 0.03, 0.65, 0.43, 0.13, 0.72])

In [56]:
np.where(array_5>0.5)


(array([0, 1, 3, 6, 9], dtype=int64),)

7 - Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [57]:
array6 = np.random.randint(0, 101, 40)
array6

array([44, 33, 57, 69, 38, 25, 95,  7, 57, 41, 35, 92, 16, 52,  7, 18, 34,
       97, 76, 19, 78, 17, 82, 54, 64,  0, 41,  4, 40,  0, 93, 80, 54, 86,
       44, 59, 29, 42, 78, 95])

In [59]:
array_6_div = [(array6 % 3 == 0) & (array6 % 4 == 0)]
array_6_div

[array([False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False,
        False, False,  True, False, False, False, False, False, False,
        False, False, False, False])]

8 - BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

# Reshape y Transpose

## Ejercicios con reshape:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [3]:
# Crear un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100
array_3d = np.random.randint(1, 101, size=(2, 3, 4))
print("Array original (3D):\n", array_3d)

# Obtener el número total de elementos en el array 3D
total_elementos = np.prod(array_3d.shape)

# Reshape del array 3D a un array 2D manteniendo el mismo número total de elementos
array_2d = array_3d.reshape(total_elementos // 4, 4)
print("\nArray convertido a 2D:\n", array_2d)


Array original (3D):
 [[[ 80  22  15  72]
  [ 33  45  92  86]
  [ 83  45  66   8]]

 [[100  20  24  95]
  [  6  98  28  16]
  [ 54  79  17  92]]]

Array convertido a 2D:
 [[ 80  22  15  72]
 [ 33  45  92  86]
 [ 83  45  66   8]
 [100  20  24  95]
 [  6  98  28  16]
 [ 54  79  17  92]]


2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [7]:
# Crear un array 3D de forma (3, 4, 5) con valores del 1 al 60 (sin incluir)
array_3d = np.arange(1, 61).reshape(3, 4, 5)
print("Array original (3D):\n", array_3d)

# Reshape del array 3D a un array 2D
array_2d = array_3d.reshape(-1, 5)
print("\nArray convertido a 2D:\n", array_2d)

Array original (3D):
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]

Array convertido a 2D:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]


3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

In [8]:
# Crear un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1
array_3d = np.random.rand(4, 3, 2)
print("Array original (3D):\n", array_3d)

# Reshape del array 3D a un array 2D
array_2d = array_3d.reshape(-1, 2)
print("\nArray convertido a 2D:\n", array_2d)

Array original (3D):
 [[[0.99924834 0.41791436]
  [0.75246183 0.9000284 ]
  [0.14356722 0.8395586 ]]

 [[0.40334952 0.63224565]
  [0.71486972 0.46503208]
  [0.69314855 0.44059469]]

 [[0.18595044 0.2749959 ]
  [0.99510394 0.52082751]
  [0.83331607 0.69135374]]

 [[0.99598737 0.4872912 ]
  [0.78491586 0.0710255 ]
  [0.95167933 0.1150893 ]]]

Array convertido a 2D:
 [[0.99924834 0.41791436]
 [0.75246183 0.9000284 ]
 [0.14356722 0.8395586 ]
 [0.40334952 0.63224565]
 [0.71486972 0.46503208]
 [0.69314855 0.44059469]
 [0.18595044 0.2749959 ]
 [0.99510394 0.52082751]
 [0.83331607 0.69135374]
 [0.99598737 0.4872912 ]
 [0.78491586 0.0710255 ]
 [0.95167933 0.1150893 ]]


## Ejercicios con transpose:

4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [9]:
# Crear el array 3D original
array_3d = np.arange(1, 61).reshape(3, 4, 5)
print("Array original (3D):\n", array_3d)

# Permutar los ejes para obtener un nuevo array con forma (5, 4, 3)
nuevo_array_3d = array_3d.transpose(2, 1, 0)
print("\nNuevo array con forma (5, 4, 3):\n", nuevo_array_3d)

Array original (3D):
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]

Nuevo array con forma (5, 4, 3):
 [[[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]

 [[ 5 25 45]
  [10 30 50]
  [15 35 55]
  [20 40 60]]]


5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

In [10]:
# Crear el array 3D original
array_3d = np.random.rand(4, 3, 2)
print("Array original (3D):\n", array_3d)

# Cambiar el orden de los ejes para obtener un nuevo array con forma (3, 2, 4)
nuevo_array_3d = array_3d.transpose(1, 2, 0)
print("\nNuevo array con forma (3, 2, 4):\n", nuevo_array_3d)

Array original (3D):
 [[[0.12590795 0.0674334 ]
  [0.83589934 0.57560462]
  [0.02688422 0.09225866]]

 [[0.68241555 0.65931607]
  [0.48014454 0.95398871]
  [0.50892055 0.11160739]]

 [[0.17821847 0.24715051]
  [0.90813215 0.00281952]
  [0.29470176 0.66826665]]

 [[0.1930527  0.31262073]
  [0.33703023 0.84166131]
  [0.93595732 0.90591541]]]

Nuevo array con forma (3, 2, 4):
 [[[0.12590795 0.68241555 0.17821847 0.1930527 ]
  [0.0674334  0.65931607 0.24715051 0.31262073]]

 [[0.83589934 0.48014454 0.90813215 0.33703023]
  [0.57560462 0.95398871 0.00281952 0.84166131]]

 [[0.02688422 0.50892055 0.29470176 0.93595732]
  [0.09225866 0.11160739 0.66826665 0.90591541]]]


## Preguntas teóricas

6. ¿Qué diferencia existe entre el reshape y el transpose?

### *reshape* se utiliza para cambiar la forma del array manteniendo los mismos datos.
 - permite cambiar las dimensiones del array siempre que el número total de elementos sea el mismo.
 - se puede convertir un array 1D en uno 2D o 3D, o modificar las dimensiones de un array manteniendo el mismo número total de elementos.

### *transpose* se utiliza para cambiar el orden de los ejes del array, alterando la disposición de los datos.
 - permite cambiar la orientación o disposición de los datos.
 - se puede cambiar un array 2D para intercambiar filas y columnas, o un array 3D para reorganizar las dimensiones.


In [15]:
#reshape
array_2_reshape = np.arange(12)  # Array de 1D con 12 elementos
reshaped_array = array_2_reshape.reshape(3, 4)  # Cambia la forma a 3 filas y 4 columnas (2D)
print("Array original 1D:\n",array_2_reshape)
print("\nArray convertido a 2D:\n", reshaped_array)

Array original 1D:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Array convertido a 2D:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
#transpose
array_2_transpose = np.array([[1, 2, 3], [4, 5, 6]])  # Array 2D con forma (2,3) - 2 filas y 3 columnas
transposed_array = array_2_transpose.T  # Transpone el array, intercambiando filas y columnas (3 filas y 2 columnas)
print("Array original 2D:\n",array_2_transpose)
print("\nNuevo array con forma (3, 2):\n",transposed_array)

Array original 2D:
 [[1 2 3]
 [4 5 6]]

Nuevo array con forma (3, 2):
 [[1 4]
 [2 5]
 [3 6]]


7. ¿Y entre el transpose y el swapaxes?

**transpose** se utiliza para **reordenar** los ejes de un array según dimensiones específicas o invertir su orden si no se especifica

**swapaxes** se utiliza **exclusivamente para intercambiar dos ejes** particulares en un array multidimensional sin cambiar la orientación de los demás ejes.

In [27]:
#transpose
array_7 = np.array([[1, 2, 3], [4, 5, 6]])  # Array 2D original
print(f"Array original {array_7.ndim}D tiene forma {array_7.shape}:\n",array_7)
transposed_array_7 = array_7.transpose()  # Cambia el orden
print(f"\nArray transpuesto es {transposed_array_7.ndim}D tiene forma {transposed_array_7.shape}\n{transposed_array_7}")

Array original 2D tiene forma (2, 3):
 [[1 2 3]
 [4 5 6]]

Array transpuesto es 2D tiene forma (3, 2)
[[1 4]
 [2 5]
 [3 6]]


In [30]:
#swapaxes

# Crear un array 3D con forma (3, 3, 5) con valores específicos
array_3d = np.array([
    [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]],
    [[16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]],
    [[31, 32, 33, 34, 35], [36, 37, 38, 39, 40], [41, 42, 43, 44, 45]]
])

print("Array original (3D) con forma (3, 3, 5):\n", array_3d)

# Intercambiar los ejes 0 y 1 usando swapaxes
swapped_axes_array = array_3d.swapaxes(0, 1)
print("\nArray con ejes intercambiados (3D) con forma (3, 3, 5) después de swapaxes:\n", swapped_axes_array)


Array original (3D) con forma (3, 3, 5):
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]

 [[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]]

Array con ejes intercambiados (3D) con forma (3, 3, 5) después de swapaxes:
 [[[ 1  2  3  4  5]
  [16 17 18 19 20]
  [31 32 33 34 35]]

 [[ 6  7  8  9 10]
  [21 22 23 24 25]
  [36 37 38 39 40]]

 [[11 12 13 14 15]
  [26 27 28 29 30]
  [41 42 43 44 45]]]


# Funciones Aritméticas y Estadísticas:

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [34]:
# Crear un array 3D de forma (2, 3, 5) con valores entre 0 y 1 con un solo decimal
array_3d = np.round(np.random.rand(2, 3, 5), 1)
print("Array 3D de forma (2, 3, 5) con valores entre 0 y 1 con un decimal:\n", array_3d)

Array 3D de forma (2, 3, 5) con valores entre 0 y 1 con un decimal:
 [[[0.5 0.1 0.7 0.2 0.3]
  [0.5 0.6 0.5 0.6 0.4]
  [0.8 1.  0.3 0.2 0.9]]

 [[0.6 0.9 0.1 0.5 0. ]
  [0.8 0.4 0.2 0.3 0.8]
  [0.1 0.3 0.  0.7 0.7]]]


2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
 - Si el valor del array es igual que la media, se reemplaza por "A".
 - Si el valor del array es mayor que la media, se reemplaza por "B".
 - Si el valor del array es menor que la media, se reemplaza por "C".
 - Si el valor es igual que el máximo, se reemplaza por "D".
 - Si el valor es igual que el mínimo, se reemplaza por "E".

In [36]:
# Obtener la media, el máximo y el mínimo del primer array
media = np.mean(array_3d)
maximo = np.max(array_3d)
minimo = np.min(array_3d)

# Crear un array vacío con la misma forma y dimensiones que array_3d
# ojo: si asigno strings al array vacío hay q definir el tipo de dato como dtype=str para q no de error al intentar convertir esos strings a números
array_vacio = np.empty_like(array_3d, dtype=str) 

# Reemplazar los valores del array_vacio según las condiciones dadas
for i in range(array_3d.shape[0]):
    for j in range(array_3d.shape[1]):
        for k in range(array_3d.shape[2]):
            valor = array_3d[i, j, k]
            if valor == media:
                array_vacio[i, j, k] = 'A'
            elif valor > media:
                array_vacio[i, j, k] = 'B'
            elif valor < media:
                array_vacio[i, j, k] = 'C'
            if valor == maximo:
                array_vacio[i, j, k] = 'D'
            if valor == minimo:
                array_vacio[i, j, k] = 'E'

print("Array vacío con los valores reemplazados:\n", array_vacio)

Array vacío con los valores reemplazados:
 [[['B' 'C' 'B' 'C' 'C']
  ['B' 'B' 'B' 'B' 'C']
  ['B' 'D' 'C' 'C' 'B']]

 [['B' 'B' 'C' 'B' 'E']
  ['B' 'C' 'C' 'C' 'B']
  ['C' 'C' 'E' 'B' 'B']]]
